[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/selection/*"
  to = "/selection/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/selection/index.html"
  status = 200
